USE [master]
GO

/****** Object:  Database [imodadb]    Script Date: 28/05/2018 16:22:21 ******/
CREATE DATABASE [imodadb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'imodadb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\imodadb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'imodadb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\imodadb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [imodadb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [imodadb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [imodadb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [imodadb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [imodadb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [imodadb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [imodadb] SET ARITHABORT OFF 
GO

ALTER DATABASE [imodadb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [imodadb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [imodadb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [imodadb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [imodadb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [imodadb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [imodadb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [imodadb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [imodadb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [imodadb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [imodadb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [imodadb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [imodadb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [imodadb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [imodadb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [imodadb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [imodadb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [imodadb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [imodadb] SET  MULTI_USER 
GO

ALTER DATABASE [imodadb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [imodadb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [imodadb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [imodadb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [imodadb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [imodadb] SET QUERY_STORE = OFF
GO

USE [imodadb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [imodadb] SET  READ_WRITE 
GO

