//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PáginaPrincipal.base_de_dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrendamento> ArrendamentoSet { get; set; }
        public virtual DbSet<Cliente> ClienteSet { get; set; }
        public virtual DbSet<Serviço> ServiçoSet { get; set; }
        public virtual DbSet<Limpeza> LimpezaSet { get; set; }

        public virtual DbSet<Venda> GetVendaSet()
        {
            return vendaSet;
        }

        public virtual void SetVendaSet(DbSet<Venda> value)
        {
            vendaSet = value;
        }

        public virtual DbSet<Casa> GetCasaSet()
        {
            return casaSet;
        }

        public virtual void SetCasaSet(DbSet<Casa> value)
        {
            casaSet = value;
        }
    }
}
